---
name: Build LaTeX PDF

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v3
      - name: Compile LaTeX document
        working-directory: thesis
        run: |
          mkdir -p build
          latexmk \
            -pdf \
            -file-line-error \
            -interaction=nonstopmode \
            -outdir=build \
            main.tex