---
name: Build LaTeX PDF

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis/main.tex
      - name: Verify PDF was generated
        run: |
          echo "Contents of thesis/ directory:"
          ls -lh thesis/
          if [ -f thesis/main.pdf ]; then
            echo "thesis/main.pdf exists."
          else
            echo "ERROR: thesis/main.pdf not found!" >&2
            exit 1
          fi
