---
name: Build LaTeX PDF

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis/main.tex
          latexmk_use_lualatex: false
          latexmk_use_xelatex: false

      - name: Upload main.pdf
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: thesis-main-pdf
          path: thesis/main.pdf
