---
name: Build LaTeX PDF

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis/main.tex
          work_in_root_file_dir: true
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: thesis.pdf
          path: thesis/main.pdf
